import {
  MarketDefaultSession,
  MarketStatus,
  EffectivityStatus,
} from "../lib/types";

export const marketDefaultSessions: MarketDefaultSession[] = [
  {
    market: "ASX",
    weekday: 1,
    start: "10:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "ASX",
    weekday: 2,
    start: "10:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "ASX",
    weekday: 3,
    start: "10:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "ASX",
    weekday: 4,
    start: "10:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "ASX",
    weekday: 5,
    start: "10:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "EURONEXT",
    weekday: 1,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "EURONEXT",
    weekday: 2,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "EURONEXT",
    weekday: 3,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "EURONEXT",
    weekday: 4,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "EURONEXT",
    weekday: 5,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },

  {
    market: "NYSE",
    weekday: 1,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "NYSE",
    weekday: 2,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "NYSE",
    weekday: 3,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "NYSE",
    weekday: 4,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "NYSE",
    weekday: 5,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },

  {
    market: "NASDAQ",
    weekday: 1,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "NASDAQ",
    weekday: 2,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "NASDAQ",
    weekday: 3,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "NASDAQ",
    weekday: 4,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "NASDAQ",
    weekday: 5,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 1,
    start: "09:30",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 1,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 1,
    start: "13:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 2,
    start: "09:30",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 2,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 2,
    start: "13:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 3,
    start: "09:30",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 3,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 3,
    start: "13:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 4,
    start: "09:30",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 4,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 4,
    start: "13:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 5,
    start: "09:30",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 5,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "HKEX",
    weekday: 5,
    start: "13:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 1,
    start: "09:00",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 1,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 1,
    start: "13:00",
    end: "17:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 2,
    start: "09:00",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 2,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 2,
    start: "13:00",
    end: "17:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 3,
    start: "09:00",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 3,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 3,
    start: "13:00",
    end: "17:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 4,
    start: "09:00",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 4,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 4,
    start: "13:00",
    end: "17:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 5,
    start: "09:00",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 5,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "SGX",
    weekday: 5,
    start: "13:00",
    end: "17:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "LSE",
    weekday: 1,
    start: "08:00",
    end: "16:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "LSE",
    weekday: 2,
    start: "08:00",
    end: "16:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "LSE",
    weekday: 3,
    start: "08:00",
    end: "16:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "LSE",
    weekday: 4,
    start: "08:00",
    end: "16:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "LSE",
    weekday: 5,
    start: "08:00",
    end: "16:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
];
