import { Market, MarketStatus } from "../lib/types";

export const markets: Market[] = [
  {
    id: "ASX",
    code: "ASX",
    name: "ASX",
    city: "Sydney",
    country: "AU",
    timezone: "Australia/Sydney",
    timezoneOffset: 10,
    longitude: 151.2099,
    capitalisation: 1320000000000,
    defaultSessions: [
      {
        weekday: 1,
        start: "10:00",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 2,
        start: "10:00",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 3,
        start: "10:00",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 4,
        start: "10:00",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 5,
        start: "10:00",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
    ],
  },
  {
    id: "EURONEXT",
    code: "EURONEXT",
    name: "EURONEXT",
    city: "Paris",
    country: "FR",
    timezone: "Europe/Paris",
    timezoneOffset: 2,
    longitude: 2.349014,
    capitalisation: 7330000000,
    defaultSessions: [
      {
        weekday: 1,
        start: "09:00",
        end: "17:29",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 2,
        start: "09:00",
        end: "17:29",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 3,
        start: "09:00",
        end: "17:29",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 4,
        start: "09:00",
        end: "17:29",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 5,
        start: "09:00",
        end: "17:29",
        status: MarketStatus.OPEN,
      },
    ],
  },
  {
    id: "NYSE",
    code: "NYSE",
    name: "NYSE",
    city: "New York",
    country: "US",
    timezone: "America/New_York",
    timezoneOffset: -4,
    longitude: -73.935242,
    capitalisation: 21040000000000,
    defaultSessions: [
      {
        weekday: 1,
        start: "09:30",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 2,
        start: "09:30",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 3,
        start: "09:30",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 4,
        start: "09:30",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 5,
        start: "09:30",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
    ],
  },
  {
    id: "NASDAQ",
    code: "NASDAQ",
    name: "NASDAQ",
    city: "New York",
    country: "US",
    timezone: "America/New_York",
    timezoneOffset: -4,
    longitude: -73.935242,
    capitalisation: 14650000000000,
    defaultSessions: [
      {
        weekday: 1,
        start: "09:30",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 2,
        start: "09:30",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 3,
        start: "09:30",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 4,
        start: "09:30",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 5,
        start: "09:30",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
    ],
  },
  {
    id: "HKEX",
    code: "HKEX",
    name: "HKEX",
    city: "Hong Kong",
    country: "CN",
    timezone: "Asia/Hong_Kong",
    timezoneOffset: 8,
    longitude: 114.177216,
    capitalisation: 4890000000000,
    defaultSessions: [
      {
        weekday: 1,
        start: "09:30",
        end: "11:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 1,
        start: "12:00",
        end: "12:59",
        status: MarketStatus.BREAK,
      },
      {
        weekday: 1,
        start: "13:00",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 2,
        start: "09:30",
        end: "11:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 2,
        start: "12:00",
        end: "12:59",
        status: MarketStatus.BREAK,
      },
      {
        weekday: 2,
        start: "13:00",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 3,
        start: "09:30",
        end: "11:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 3,
        start: "12:00",
        end: "12:59",
        status: MarketStatus.BREAK,
      },
      {
        weekday: 3,
        start: "13:00",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 4,
        start: "09:30",
        end: "11:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 4,
        start: "12:00",
        end: "12:59",
        status: MarketStatus.BREAK,
      },
      {
        weekday: 4,
        start: "13:00",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 5,
        start: "09:30",
        end: "11:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 5,
        start: "12:00",
        end: "12:59",
        status: MarketStatus.BREAK,
      },
      {
        weekday: 5,
        start: "13:00",
        end: "15:59",
        status: MarketStatus.OPEN,
      },
    ],
  },
  {
    id: "SGX",
    code: "SGX",
    name: "SGX",
    city: "Singapore",
    country: "SG",
    timezone: "Asia/Singapore",
    timezoneOffset: 8,
    longitude: 103.851959,
    capitalisation: 585920000000,
    defaultSessions: [
      {
        weekday: 1,
        start: "09:00",
        end: "11:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 1,
        start: "12:00",
        end: "12:59",
        status: MarketStatus.BREAK,
      },
      {
        weekday: 1,
        start: "13:00",
        end: "16:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 2,
        start: "09:00",
        end: "11:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 2,
        start: "12:00",
        end: "12:59",
        status: MarketStatus.BREAK,
      },
      {
        weekday: 2,
        start: "13:00",
        end: "16:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 3,
        start: "09:00",
        end: "11:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 3,
        start: "12:00",
        end: "12:59",
        status: MarketStatus.BREAK,
      },
      {
        weekday: 3,
        start: "13:00",
        end: "16:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 4,
        start: "09:00",
        end: "11:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 4,
        start: "12:00",
        end: "12:59",
        status: MarketStatus.BREAK,
      },
      {
        weekday: 4,
        start: "13:00",
        end: "16:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 5,
        start: "09:00",
        end: "11:59",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 5,
        start: "12:00",
        end: "12:59",
        status: MarketStatus.BREAK,
      },
      {
        weekday: 5,
        start: "13:00",
        end: "16:59",
        status: MarketStatus.OPEN,
      },
    ],
  },
  {
    id: "LSE",
    code: "LSE",
    name: "LSE",
    city: "London",
    country: "GB",
    timezone: "Europe/London",
    timezoneOffset: 1,
    longitude: -0.118092,
    capitalisation: 3230000000000,
    defaultSessions: [
      {
        weekday: 1,
        start: "08:00",
        end: "16:29",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 2,
        start: "08:00",
        end: "16:29",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 3,
        start: "08:00",
        end: "16:29",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 4,
        start: "08:00",
        end: "16:29",
        status: MarketStatus.OPEN,
      },
      {
        weekday: 5,
        start: "08:00",
        end: "16:29",
        status: MarketStatus.OPEN,
      },
    ],
  },
];
