import {
  MarketDefaultSession,
  MarketStatus,
  EffectivityStatus,
} from "../lib/types";

export const marketDefaultSessions: MarketDefaultSession[] = [
  {
    market: "XNYS",
    weekday: 1,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNYS",
    weekday: 2,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNYS",
    weekday: 3,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNYS",
    weekday: 4,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNYS",
    weekday: 5,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNAS",
    weekday: 1,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNAS",
    weekday: 2,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNAS",
    weekday: 3,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNAS",
    weekday: 4,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNAS",
    weekday: 5,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XLON",
    weekday: 1,
    start: "08:00",
    end: "16:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XLON",
    weekday: 2,
    start: "08:00",
    end: "16:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XLON",
    weekday: 3,
    start: "08:00",
    end: "16:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XLON",
    weekday: 4,
    start: "08:00",
    end: "16:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XLON",
    weekday: 5,
    start: "08:00",
    end: "16:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 1,
    start: "09:00",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 1,
    start: "11:30",
    end: "12:30",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 1,
    start: "12:30",
    end: "15:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 2,
    start: "09:00",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 2,
    start: "11:30",
    end: "12:30",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 2,
    start: "12:30",
    end: "15:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 3,
    start: "09:00",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 3,
    start: "11:30",
    end: "12:30",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 3,
    start: "12:30",
    end: "15:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 4,
    start: "09:00",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 4,
    start: "11:30",
    end: "12:30",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 4,
    start: "12:30",
    end: "15:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 5,
    start: "09:00",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 5,
    start: "11:30",
    end: "12:30",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XJPX",
    weekday: 5,
    start: "12:30",
    end: "15:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 1,
    start: "09:30",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 1,
    start: "11:30",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 1,
    start: "13:00",
    end: "15:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 2,
    start: "09:30",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 2,
    start: "11:30",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 2,
    start: "13:00",
    end: "15:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 3,
    start: "09:30",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 3,
    start: "11:30",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 3,
    start: "13:00",
    end: "15:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 4,
    start: "09:30",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 4,
    start: "11:30",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 4,
    start: "13:00",
    end: "15:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 5,
    start: "09:30",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 5,
    start: "11:30",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHG",
    weekday: 5,
    start: "13:00",
    end: "15:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 1,
    start: "09:30",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 1,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 1,
    start: "13:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 2,
    start: "09:30",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 2,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 2,
    start: "13:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 3,
    start: "09:30",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 3,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 3,
    start: "13:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 4,
    start: "09:30",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 4,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 4,
    start: "13:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 5,
    start: "09:30",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 5,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XHKG",
    weekday: 5,
    start: "13:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XAMS",
    weekday: 1,
    start: "09:00",
    end: "17:40",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XAMS",
    weekday: 2,
    start: "09:00",
    end: "17:40",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XAMS",
    weekday: 3,
    start: "09:00",
    end: "17:40",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XAMS",
    weekday: 4,
    start: "09:00",
    end: "17:40",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XAMS",
    weekday: 5,
    start: "09:00",
    end: "17:40",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 1,
    start: "09:30",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 1,
    start: "11:30",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 1,
    start: "13:00",
    end: "14:57",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 2,
    start: "09:30",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 2,
    start: "11:30",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 2,
    start: "13:00",
    end: "14:57",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 3,
    start: "09:30",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 3,
    start: "11:30",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 3,
    start: "13:00",
    end: "14:57",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 4,
    start: "09:30",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 4,
    start: "11:30",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 4,
    start: "13:00",
    end: "14:57",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 5,
    start: "09:30",
    end: "11:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 5,
    start: "11:30",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSHE",
    weekday: 5,
    start: "13:00",
    end: "14:57",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XTSE",
    weekday: 1,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XTSE",
    weekday: 2,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XTSE",
    weekday: 3,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XTSE",
    weekday: 4,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XTSE",
    weekday: 5,
    start: "09:30",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XBOM",
    weekday: 1,
    start: "09:15",
    end: "15:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XBOM",
    weekday: 2,
    start: "09:15",
    end: "15:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XBOM",
    weekday: 3,
    start: "09:15",
    end: "15:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XBOM",
    weekday: 4,
    start: "09:15",
    end: "15:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XBOM",
    weekday: 5,
    start: "09:15",
    end: "15:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XASX",
    weekday: 1,
    start: "10:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XASX",
    weekday: 2,
    start: "10:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XASX",
    weekday: 3,
    start: "10:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XASX",
    weekday: 4,
    start: "10:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XASX",
    weekday: 5,
    start: "10:00",
    end: "16:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XMAD",
    weekday: 1,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XMAD",
    weekday: 2,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XMAD",
    weekday: 3,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XMAD",
    weekday: 4,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XMAD",
    weekday: 5,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNZE",
    weekday: 1,
    start: "10:00",
    end: "16:45",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNZE",
    weekday: 2,
    start: "10:00",
    end: "16:45",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNZE",
    weekday: 3,
    start: "10:00",
    end: "16:45",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNZE",
    weekday: 4,
    start: "10:00",
    end: "16:45",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XNZE",
    weekday: 5,
    start: "10:00",
    end: "16:45",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 1,
    start: "09:00",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 1,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 1,
    start: "13:00",
    end: "17:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 2,
    start: "09:00",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 2,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 2,
    start: "13:00",
    end: "17:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 3,
    start: "09:00",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 3,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 3,
    start: "13:00",
    end: "17:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 4,
    start: "09:00",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 4,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 4,
    start: "13:00",
    end: "17:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 5,
    start: "09:00",
    end: "12:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 5,
    start: "12:00",
    end: "13:00",
    status: MarketStatus.BREAK,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XSES",
    weekday: 5,
    start: "13:00",
    end: "17:00",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XPAR",
    weekday: 1,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XPAR",
    weekday: 2,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XPAR",
    weekday: 3,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XPAR",
    weekday: 4,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XPAR",
    weekday: 5,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XBRU",
    weekday: 1,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XBRU",
    weekday: 2,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XBRU",
    weekday: 3,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XBRU",
    weekday: 4,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XBRU",
    weekday: 5,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XLIS",
    weekday: 1,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XLIS",
    weekday: 2,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XLIS",
    weekday: 3,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XLIS",
    weekday: 4,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XLIS",
    weekday: 5,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XETR",
    weekday: 1,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XETR",
    weekday: 2,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XETR",
    weekday: 3,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XETR",
    weekday: 4,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XETR",
    weekday: 5,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XMIL",
    weekday: 1,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XMIL",
    weekday: 2,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XMIL",
    weekday: 3,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XMIL",
    weekday: 4,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
  {
    market: "XMIL",
    weekday: 5,
    start: "09:00",
    end: "17:30",
    status: MarketStatus.OPEN,
    effectivity: {
      status: EffectivityStatus.ACTIVE,
      startDate: "2000-01-01",
    },
  },
];
