import { Market } from "../lib/types";

export const markets: Market[] = [
  {
    id: "XNYS",
    mic: "XNYS",
    shortName: "NYSE",
    name: "New York Stock Exchange",
    currency: "USD",
    city: "New York",
    country: "US",
    timezone: "America/New_York",
    latitude: 40.6943,
    longitude: -73.9249,
    capitalisation: 22923,
    website: "www.nyse.com",
  },
  {
    id: "XNAS",
    mic: "XNAS",
    shortName: "NASDAQ",
    name: "NASDAQ Stock Exchange",
    currency: "USD",
    city: "New York",
    country: "US",
    timezone: "America/New_York",
    latitude: 40.6943,
    longitude: -73.9249,
    capitalisation: 10857,
    website: "www.nasdaq.com",
  },
  {
    id: "XLON",
    mic: "XLON",
    shortName: "LSE",
    name: "London Stock Exchange",
    currency: "GBP",
    city: "London",
    country: "GB",
    timezone: "Europe/London",
    latitude: 51.5072,
    longitude: -0.1275,
    capitalisation: 4590,
    website: "www.londonstockexchange.com",
  },
  {
    id: "XJPX",
    mic: "XJPX",
    shortName: "JPX",
    name: "Tokyo Stock Exchange",
    currency: "JPY",
    city: "Tokyo",
    country: "JP",
    timezone: "Asia/Tokyo",
    latitude: 35.6897,
    longitude: 139.6922,
    capitalisation: 5679,
    website: "www.jpx.co.jp",
  },
  {
    id: "XSHG",
    mic: "XSHG",
    shortName: "SSE",
    name: "Shanghai Stock Exchange",
    currency: "CNY",
    city: "Shanghai",
    country: "CN",
    timezone: "Asia/Shanghai",
    latitude: 31.1667,
    longitude: 121.4667,
    capitalisation: 4026,
    website: "english.sse.com.cn",
  },
  {
    id: "XHKG",
    mic: "XHKG",
    shortName: "HKEX",
    name: "Hong Kong Stock Exchange",
    currency: "HKD",
    city: "Hong Kong",
    country: "HK",
    timezone: "Asia/Hong_Kong",
    latitude: 22.305,
    longitude: 114.185,
    capitalisation: 3936,
    website: "www.hkex.com.hk",
  },
  {
    id: "XAMS",
    mic: "XAMS",
    shortName: "XAMS",
    name: "Euronext Amsterdam",
    currency: "EUR",
    city: "Amsterdam",
    country: "NL",
    timezone: "Europe/Amsterdam",
    latitude: 52.35,
    longitude: 4.9166,
    capitalisation: 3927,
    website: "www.euronext.com",
  },
  {
    id: "XSHE",
    mic: "XSHE",
    shortName: "SZSE",
    name: "Shenzhen Stock Exchange",
    currency: "CNY",
    city: "Shenzhen",
    country: "CN",
    timezone: "Asia/Shanghai",
    latitude: 22.535,
    longitude: 114.054,
    capitalisation: 2504,
    website: "www.szse.cn",
  },
  {
    id: "XTSE",
    mic: "XTSE",
    shortName: "TSX",
    name: "Toronto Stock Exchange",
    currency: "CAD",
    city: "Toronto",
    country: "CA",
    timezone: "America/Toronto",
    latitude: 43.7417,
    longitude: -79.3733,
    capitalisation: 3256,
    website: "www.tmx.com",
  },
  {
    id: "XBOM",
    mic: "XBOM",
    shortName: "BSE",
    name: "Bombay Stock Exchange",
    currency: "INR",
    city: "Mumbai",
    country: "IN",
    timezone: "Asia/Kolkata",
    latitude: 18.9667,
    longitude: 72.8333,
    capitalisation: 2056,
    website: "www.bseindia.com",
  },
  {
    id: "XASX",
    mic: "XASX",
    shortName: "ASX",
    name: "Australia Stock Exchange",
    currency: "AUD",
    city: "Sydney",
    country: "AU",
    timezone: "Australia/Sydney",
    latitude: -33.865,
    longitude: 151.2094,
    capitalisation: 1328,
    website: "www.asx.com.au",
  },
  {
    id: "XMAD",
    mic: "XMAD",
    shortName: "BME",
    name: "Madrid Stock Exchange",
    currency: "EUR",
    city: "Madrid",
    country: "ES",
    timezone: "Europe/Madrid",
    latitude: 40.4189,
    longitude: -3.6919,
    capitalisation: 764,
    website: "www.bolsamadrid.es",
  },
  {
    id: "XNZE",
    mic: "XNZE",
    shortName: "NZX",
    name: "New Zealand Stock Exchange",
    currency: "NZD",
    city: "Wellington",
    country: "NZ",
    timezone: "Pacific/Auckland",
    latitude: -41.2889,
    longitude: 174.7772,
    capitalisation: 107,
    website: "www.nzx.com",
  },
  {
    id: "XSES",
    mic: "XSES",
    shortName: "SGX",
    name: "Singapore Exchange",
    currency: "SGD",
    city: "Singapore",
    country: "SG",
    timezone: "Asia/Singapore",
    latitude: 1.3,
    longitude: 103.8,
    capitalisation: 583,
    website: "www.sgx.com",
  },
  {
    id: "XPAR",
    mic: "XPAR",
    shortName: "XPAR",
    name: "Euronext Paris",
    currency: "EUR",
    city: "Paris",
    country: "FR",
    timezone: "Europe/Paris",
    latitude: 48.8566,
    longitude: 2.3522,
    capitalisation: 3927,
    website: "www.euronext.com",
  },
  {
    id: "XBRU",
    mic: "XBRU",
    shortName: "XBRU",
    name: "Euronext Brussels",
    currency: "EUR",
    city: "Brussels",
    country: "BE",
    timezone: "Europe/Brussels",
    latitude: 50.8467,
    longitude: 4.3517,
    capitalisation: 3927,
    website: "www.euronext.com",
  },
  {
    id: "XLIS",
    mic: "XLIS",
    shortName: "XLIS",
    name: "Euronext Lisbon",
    currency: "EUR",
    city: "Lisbon",
    country: "PT",
    timezone: "Europe/Lisbon",
    latitude: 38.7452,
    longitude: -9.1604,
    capitalisation: 3927,
    website: "www.euronext.com",
  },
  {
    id: "XETR",
    mic: "XETR",
    shortName: "XETR",
    name: "Deutsche Börse Xetra",
    currency: "EUR",
    city: "Frankfurt",
    country: "DE",
    timezone: "Europe/Berlin",
    latitude: 50.1136,
    longitude: 8.6797,
    capitalisation: 1864,
    website: "www.deutsche-boerse.com",
  },
  {
    id: "XMIL",
    mic: "XMIL",
    shortName: "MTA",
    name: "Italian Stock Exchange",
    currency: "EUR",
    city: "Milan",
    country: "IT",
    timezone: "Europe/Rome",
    latitude: 45.4669,
    longitude: 9.19,
    capitalisation: 567,
    website: "www.borsaitaliana.it",
  },
];
